services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - network_api
    depends_on:
      - db
    entrypoint: sh ./.docker/entrypoint.sh
    ports:
      - "9000:9000"

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: userpass123
      MYSQL_PASSWORD: userpass123
      MYSQL_USER: root-docker
    volumes:
      - dbdata:/docker-entrypoint-initdb.d
    networks:
      - network_api
    ports:
      - 33060:3306

networks:
  network_api:
    driver: bridge

volumes:
  dbdata: